"""
    Author : Tejaswini Ramesh Nimbalkar.
"""
# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'evaluateteam.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

# Connection to database
# If project does not connect with database, provide full path to databse
# e.g. - 'C:\\Python36\\fantcktdb.db'
import sqlite3
db=sqlite3.connect('fantcktdb.db')
cur=db.cursor()

class Ui_Dialog_Evaluate(object):
    # Do not edit this function as it is system generated
    def setupUiEvaluate(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(763, 642)
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout_3.addWidget(self.label)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.selectTeam = QtWidgets.QComboBox(Dialog)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        self.selectTeam.setFont(font)
        self.selectTeam.setObjectName("selectTeam")
        self.selectTeam.addItem("")
        self.selectTeam.activated.connect(self.showPlayers)
        self.horizontalLayout.addWidget(self.selectTeam)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.selectMatch = QtWidgets.QComboBox(Dialog)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        self.selectMatch.setFont(font)
        self.selectMatch.setObjectName("selectMatch")
        self.selectMatch.addItem("")
        self.horizontalLayout.addWidget(self.selectMatch)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.line = QtWidgets.QFrame(Dialog)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_3.addWidget(self.line)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.pLabel = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pLabel.setFont(font)
        self.pLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.pLabel.setObjectName("pLabel")
        self.verticalLayout.addWidget(self.pLabel)
        self.playerList = QtWidgets.QListWidget(Dialog)
        self.playerList.setObjectName("playerList")
        self.verticalLayout.addWidget(self.playerList)
        self.horizontalLayout_3.addLayout(self.verticalLayout)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.ptLabel = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.ptLabel.setFont(font)
        self.ptLabel.setObjectName("ptLabel")
        self.ptLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.horizontalLayout_2.addWidget(self.ptLabel)
        self.ptNo = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        self.ptNo.setFont(font)
        self.ptNo.setText("")
        self.ptNo.setObjectName("ptNo")
        self.horizontalLayout_2.addWidget(self.ptNo)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.pointList = QtWidgets.QListWidget(Dialog)
        self.pointList.setObjectName("pointList")
        self.verticalLayout_2.addWidget(self.pointList)
        self.horizontalLayout_3.addLayout(self.verticalLayout_2)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.calcButton = QtWidgets.QPushButton(Dialog)
        self.calcButton.setMinimumSize(QtCore.QSize(120, 28))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        self.calcButton.setFont(font)
        self.calcButton.setObjectName("calcButton")
        self.calcButton.clicked.connect(self.calcScore)
        self.verticalLayout_3.addWidget(self.calcButton)
        self.score = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        font.setBold(True)
        self.score.setFont(font)
        self.score.setAlignment(QtCore.Qt.AlignCenter)
        self.score.setObjectName("score")
        self.score.setText("Team Score : ")
        self.verticalLayout_3.addWidget(self.score)
        self.gridLayout.addLayout(self.verticalLayout_3, 0, 0, 1, 1)

        # add items to teams list 
        cur.execute("SELECT TName FROM teams")
        records=cur.fetchall()
        records=list(set(records))
        for row in records:
            self.selectTeam.addItem(row[0])

        # add items to matches list
        cur.execute("SELECT MName FROM matches")
        records=cur.fetchall()
        records=list(set(records))
        for row in records:
            self.selectMatch.addItem(row[0])

        self.retranslateUiEvaluate(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    # Do not edit this function as it is system generated
    def retranslateUiEvaluate(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Evaluate Team"))
        self.label.setText(_translate("Dialog", "Evaluate the performance of your Fantasy Team"))
        self.selectTeam.setItemText(0, _translate("Dialog", "Select Team"))
        self.selectMatch.setItemText(0, _translate("Dialog", "Select Match"))
        self.pLabel.setText(_translate("Dialog", "Palyers"))
        self.ptLabel.setText(_translate("Dialog", "Points"))
        self.calcButton.setText(_translate("Dialog", "Calculate Score"))

    # function for displaying players in list
    def showPlayers(self, Dialog):
        tname=self.selectTeam.currentText()
        cur.execute("SELECT Players FROM teams WHERE TName='"+tname+"';")
        records=cur.fetchone()
        players=records[0].split(',')
        self.playerList.clear()
        for item in players:
            self.playerList.addItem(item)

    # function for calculating score of selcted team for selected match
    def calcScore(self):
        mname=self.selectMatch.currentText()
        tscore=0
        self.pointList.clear()
        for i in range(self.playerList.count()):
            pname=self.playerList.item(i).text()
            res=cur.execute("SELECT * FROM '"+mname+"' WHERE Player='"+pname+"';")
            row=cur.fetchone()
            total,batscore,bowlscore,fieldscore=0,0,0,0
            runs=row[1]
            ballf=row[2]
            four=row[3]
            six=row[4]
            bowled=row[5]
            ballg=row[7]
            wkt=row[8]
            catches=row[9]
            stumping=row[10]
            runout=row[11]
            ctg=row[12]
            
            batscore=int(runs/2)
            if batscore>=50: batscore+=5
            if batscore>=100: batscore+=10
            if runs>0:
                sr=runs*100/ballf
                if sr>=80 and sr<100: batscore+=2
                if sr>=100:batscore+=4
            batscore=batscore+four
            batscore=batscore+2*six
            
            bowlscore=wkt*10
            if wkt>=3: bowlscore=bowlscore+5
            if wkt>=5: bowlscore=bowlscore+10
            if ballg>0:
                er=6*ballg/bowled
                if er<=2: bowlscore=bowlscore+10
                if er>2 and er<=3.5: bowlscore=bowlscore+7
                if er>3.5 and er<=4.5: bowlscore=bowlscore+4

            fieldscore=(catches+stumping+runout)*10
            
            total=batscore+bowlscore+fieldscore

            self.pointList.addItem(str(total))

            tscore=tscore+total

        self.score.setText("Team Score : {}".format(str(tscore))) 

##if __name__ == "__main__":
##    import sys
##    app = QtWidgets.QApplication(sys.argv)
##    Dialog = QtWidgets.QDialog()
##    ui = Ui_Dialog_Evaluate()
##    ui.setupUiEvaluate(Dialog)
##    Dialog.show()
##    sys.exit(app.exec_())
